dependencies:
  - smartcontractkit/chainlink@1.13.0
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.13.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2'
dotenv: .env
networks:
  default: development
wallets:
  from_key: ${PRIVATE_KEY}